# Generated by Django 4.2.1 on 2023-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPostDataItem',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('post_upload', models.TextField()),
                ('post_headline', models.TextField(null=True)),
                ('post_upvotes', models.TextField()),
                ('post_comments', models.TextField()),
                ('post_rewards', models.TextField()),
                ('post_page_links', models.TextField()),
                ('redditor', models.TextField()),
            ],
        ),
    ]
